name: Tests

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.x' ]

    name: pytest ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        shell: bash
        run: |
          uv run --frozen pytest
